<?php

/**
 * @file
 * Threads the custom script for this module to be loaded on the page.
 */
function related_content_loader_page_attachments_alter(&$page){

  $page['#attached']['library'][] = 'related_content_loader/related-content-loader';

}

/*
function parkson_subsegments_close_products_window_ajax_callback() {

  // Add the javascript with important controls for the current module.
  $module_path = drupal_get_path('module', 'parkson_subsegments_products');
  drupal_add_js($module_path. '/js/parkson_subsegments_products.js', 'file');

  // Proceeds with the appropriate replacements.
  $commands = array();

  // Fades out the products container.
  $commands[] = ajax_command_invoke('.industrial-subsegment-products', 'fadeOut');

  // Fades in other layers (not the one corresponding to the Subsegment clicked)
  $commands[] = ajax_command_invoke(
    NULL,
    "restoreDefaults",
    array(
      array(
        'target' => ".industry-subsegment-wrapper",
        'speed_transition' => 250
      )
    )
  );

  // Fades in other layers (not the one corresponding to the Industrial application clicked)
  $commands[] = ajax_command_invoke(
    NULL,
    "restoreDefaults",
    array(
      array(
        'target' => ".node-industrial-application",
        'speed_transition' => 250
      )
    )
  );

  // Scrolls to the top of the Subsegments block
  $commands[] = ajax_command_invoke(
    NULL,
    "scrollTo",
    array(
      array(
        'target' => "#node-full-content-subsegments-wrapper",
        'speed_transition' => 500,
      )
    )
  );

  $page = array(
    '#type' => 'ajax',
    '#commands' => $commands,
  );

  ajax_deliver($page);

}
*/
